### ISSUE TITLE
[to feat] QuantLab 실제 데이터를 활용하여 그래프 ui 개선

### ISSUE THREAD

**Issue by JeonYoungHo-youjeon** [economicus/economicus-fe#19]
백엔드 팀에 부탁해서 랜덤 데이터 받아왔음. 

해당 데이터를 이용해서 어떻게 구현해야하는지 확인하고 ui 체크해서 정상적으로 보이는지 확인

**Comment by moon9ua** [comment]
일단 완료된 이슈이므로 이슈 닫도록 하겠습니다.
