### ISSUE TITLE
[to fix] 로그인시 비밀번호 노출 경고

### ISSUE THREAD

**Issue by moon9ua** [economicus/economicus-fe#23]
![image](https://user-images.githubusercontent.com/59914775/155536351-a2c3a36d-b782-45cc-9af1-34a3130b932a.png)

**Comment by JeonYoungHo-youjeon** [comment]
https://devport.tistory.com/16

서버를 다시 열면 확인해봐야겠지만 개발 당시 아이디가 admin 비밀번호가 1234 여서 생긴 문제가 아닐까 합니다

**Comment by moon9ua** [comment]
감사합니다! 해당 이슈 닫겠습니다.
