### ISSUE TITLE
create quant api의 response 구조 변화에 따른 임시 조치

### ISSUE THREAD

**Issue by moon9ua** [economicus/economicus-fe#48]
* 백엔드에서 create quant api의 response 구조가 다음과 같이 변경되었습니다.
  ```
  {
      "quant_id": 4,
      "cumulative_return": 10.152285221083446,
      "annual_average_return": 0,
      "winning_percentage": 11.666666666666666,
      "max_loss_rate": -32.10196948146531,
      "holdings_count": 0,
      "chart_data": {
          "profit_rate_data": [
              // 생략
          ]
      }
  }
  ```
* 따라서 원래 사용하던 정규화 함수 등을 주석처리해 임시조치(돌아만 가도록) 하였습니다. 추후 수정이 필요합니다.
  <img width="734" alt="image" src="https://user-images.githubusercontent.com/59914775/157391123-a87522dc-0e25-4713-8ef6-cf434d46a735.png">
* 한편 날짜(start_date, end_date)에 대해 정확히 정해진 바가 없어 논의가 필요할 것 같습니다.

**Comment by JeonYoungHo-youjeon** [comment]
정규화 함수는 제가 주말까지 확인하겠습니다
